import { initFederation } from '@angular-architects/native-federation';
import { environment } from './environments/environment';

/**
 * Bootstrap sequence with runtime-config override.
 * Fetches /assets/config.json (generated by container entrypoint) and merges
 * it into the environment object before bootstrap.
 */
async function start(): Promise<void> {
  try {
    const res = await fetch('/assets/config.json', { cache: 'no-store' });
    if (res.ok) {
      const runtime = (await res.json()) as Partial<typeof environment>;
      Object.assign(environment, runtime);
      console.log('[portal] Runtime config loaded:', runtime);
    }
  } catch (err) {
    console.warn('[portal] No runtime config — using compile-time defaults', err);
  }

  try {
    await initFederation();
    await import('./bootstrap');
  } catch (err) {
    console.error('[portal] Bootstrap failed:', err);
  }
}

start();
